# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'KeyboardTest' do

pod 'Masonry', '~> 0.6.3'
pod 'pop', '~> 1.0.8'
pod 'FLKAutoLayout', '~> 0.2.1'
pod 'AFNetworking', '~> 2.6.0'

end


